### ISSUE TITLE
Multiple results with the same name do not appear to be addressed.

### ISSUE THREAD

**Issue by SuncoastGuy** [Jesmaster/Discord-BGG-Bot#101]
Hello,

The command  /search Djinn  returned:  https://boardgamegeek.com/boardgame/384150/djinn
However, this also exists:  https://boardgamegeek.com/boardgame/243698/djinn

Neither  /search Djinn (2018)  nor  /search Djinn 2018 returned any result.
Preferably,  /search Djinn  would briefly list both, with an option to choose the desired game.
or, if I am missing the proper syntax, could it be added to the readme or /help ?

Thanks for the bot.
Regards.

**Comment by Jesmaster** [comment]
Hi @SuncoastGuy

There isn't really anything I can do about this, the bot uses the same search as the autocomplete on the boardgamegeek.com search bar on the top right of the site. You'll see the same thing happen there.

The search functionality in their XML API is even worse so unfortunately I can't do anything here. It's up to them to improve their search.
