### ISSUE TITLE
No result found for "username"

### ISSUE THREAD

**Issue by sloika** [Jesmaster/Discord-BGG-Bot#80]
Now that the bot is back online, I tried using the search and it works wonderfully. However, the /collection always returns the error like in the title. I tried using 3 different usernames and make sure those usernames are correct.

**Comment by Jesmaster** [comment]
Looks like something changed with the BGG Collections API causing the collection command to not work anymore.
I'll take a look at this.

**Comment by Jesmaster** [comment]
Looks like it does work but it's not waiting long enough for the initial request. If you get no result the first time you can try the same command again and it will return correctly.

Need to increase the amount of time to wait for the second request if the result in the first request returns a 202 response.

**Comment by Jesmaster** [comment]
This will now attempt the api call up to 5 times with a two second wait between each. Should be more than enough time to for them to build the data on their end and have it ready on time.
