### ISSUE TITLE
Suggest function is broken on mobile 

### ISSUE THREAD

**Issue by mo0man** [Jesmaster/Discord-BGG-Bot#81]
/Suggest does not work work currently, it gives an error saying that whatever option entered is 'Not a Valid Choice'

**Comment by Jesmaster** [comment]
The extra paramater works differently on mobile than on desktop, will need to update the code to be able to pass a Y or N to this so it will work on mobile.

**Comment by Jesmaster** [comment]
@mo0man it actually does work on mobile. The Discord UX is a little strange here so it was easy to miss. When you select the suggest option you will see the words "Suggest to play this game?" above in bold. That is what you need to click on.

![suggest](https://user-images.githubusercontent.com/1197834/198846614-bebc187c-aefa-4314-9c39-b2429abfb01a.png)
