### ISSUE TITLE
Bot icon outdated

### ISSUE THREAD

**Issue by zaubertee** [Jesmaster/Discord-BGG-Bot#94]
Hi! I'm a big fan of the bot, but couldn't help but notice that the icon of the bot still is the old BGG mascot. I think for a more modern look it would be nice to have the clean orange icon as the bot icon. :)
Would love to see it on the bot!

![bgg icon](https://github.com/Jesmaster/Discord-BGG-Bot/assets/78155653/5606c353-a69e-4a96-8000-06a066c609ed)

**Comment by Jesmaster** [comment]
I've updated to the new image, thanks!
